# Generated by Django 5.0.2 on 2025-07-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Tech'), ('E', 'Electronic'), ('G', 'Grocery'), ('C', 'Cloth')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
