# Generated by Django 5.0.2 on 2025-07-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_attribute_alter_product_category_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='attribute',
            new_name='attributes',
        ),
    ]
