# Generated by Django 5.2.5 on 2025-09-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_product_slug_alter_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='publisher',
        ),
    ]
