# Generated by Django 5.0.2 on 2025-07-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_cart_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
    ]
