# Generated by Django 5.0.2 on 2025-07-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_cartitems_attributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='attributes',
            new_name='selected_attributes',
        ),
    ]
